name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v2.4.0
      - name: Setup
        run: |
          npm install
          sudo apt-get update
          sudo apt-get install -y reuse gnome-shell-extensions gettext

      - name: Lint
        run: make lint

      - name: Build
        run: make all

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          generate_release_notes: true
          files: |
            target/default/ShutdownTimer@deminder.shell-extension.zip
