name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch or ego-compatible
  push:
    branches: [ master, ego-compatible ]
  pull_request:
    branches: [ master, ego-compatible ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
      - name: Setup build dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get install -y reuse gnome-shell-extensions gettext
      
      - name: Run linter
        run: make lint

      - name: Build debug and default zip
        run: make all
